import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'mushrooms': "Mushrooms",
          'settings': "Settings",
          'home': "Home",
          'language': "LANGUAGE SETTINGS",
          'social': "SOCIAL MEDIA",
          'shareDeepMush': "SHARE DeepMush",
          'share_rate': "Share and rate DeepMush",
          'feedback': "FEEDBACK",
          'rate_mail': "Rate DeepMush or contact us by mail.",
          'toastgoogleplay': "Redirects to Google Play",
          'toastmail': "Redirects to Mail",
          'toastgallery': "Please choose a photo",
          'toastcamera': "Please take a photo",
          'moreinfo': "Click for more",
          'medicalassitance': "Medical Assistance",
          'ediblemushrooms': "Edible Mushrooms",
          'poisonousmushrooms': "Poisonous Mushrooms",
          'whatdeepmush': "WHAT IS DeepMush?",
          'whatdeepmushtext':
              "DeepMush is an application developed using artificial intelligence. DeepMush was developed using artificial intelligence by collecting approximately twenty thousand images of the most common poisonous and non-poisonous mushrooms in the world. DeepMush's purpose is for INFORMATION purposes only. Collecting and identifying mushrooms is definitely a matter of expertise. According to the information in DeepMush, we do not recommend that you collect or consume mushrooms!\n",
          'howisworking': "HOW IS IT WORKING",
          'howisworkingtext':
              "The application works with Artificial Intelligence. Approximately twenty thousand mushroom images were collected for the application and the Deep Learning network was trained using these images. CNN (Convolutional Neural Network) was used as the network structure and Keras library was used.\n",
          'attention': "ATTENTION\n",
          'attentiontext':
              "This application is created only for INFORMATION purposes and we do not advise to use it for checking ediblity of products. We do not own any responsiblity for potential hazards and errors.\n\nDeepMush's purpose is for INFORMATION purposes only. Collecting and identifying mushrooms is definitely a matter of expertise. According to the information in DeepMush, we do not recommend that you collect or consume mushrooms!\n",
          'mushroomstext':
              """First of all, completely, clearly, 100% without a doubt, just in case a mushroom you see is safe to eat, don't eat it at that point. . A few mushrooms can make you sick or die if eaten. In fact, if you think this is reasonably safe, if you are not completely beyond doubt, there is no reason to endanger your health. Up to this point, this mushroom cultivation cannot be direct or authoritative. We are confident that we will encourage you to get started or interested, but do not do anything dangerous based on the information in the app.\n\nThe structure of a mushroom is as follows. You can tell if a mushroom is poisonous or edible by looking at these areas of the mushroom.\n\n""",
          'attentiongiris':
              "This application is created only for INFORMATION purposes and we do not advise to use it for checking ediblity of products. Collecting and identifying mushrooms is definitely a matter of expertise. According to the information in DeepMush, we do not recommend that you collect or consume mushrooms. We do not own any responsiblity for potential hazards and errors.",
          'agree': "Agree",
          'takephptporgalery': "Take a Photo or Choose From The Gallery",
          'dg': "Percentage of Accuracy",
          '0 Poisonous': "0 Poisonous",
          '1 Edible': "1 Edible",
          '2 Undefined': "2 Undefined",
          'share': "Share",
          'rate': "Feedback",
          'contact': "Contact",
          'mushroomstext2':
              """Cap: The cap is the best of the mushroom (and frequently looks sort of like a little umbrella). Mushroom caps can come in a assortment of colors but most frequently are brown, white, or yellow.\n\nGills, Pores, or Teeth: These structures show up beneath the mushroom's cap. They see comparative to a fish's gills.\n\nRing: The ring (some of the time called the annulus) is the remaining structure of the fractional cloak after the gills have pushed through.\n\nStem or Stipe: The stem is the tall structure that holds the cap tall over the ground.\n\nVolva: The volva is the defensive cloak that remains after the mushroom grown up from the ground. As the organism develops, it breaks through the volva.\n\nSpores: Tiny seeds acting as regenerative operators; they are ordinarily discharged into the discuss and drop on a substrate to create a unused mushroom.\n\nVolva: The volva is the protective veil that remains after the mushroom sprouted up from the ground. As the fungus grows, it breaks through the volva.""",
          'edibletext':
              """In the event that you spend any time outside, you've likely seen mushrooms developing beneath trees or in your yard, but in the event that you're out camping or fair appreciate scavenging, here are a few ways to tell in the event that the mushroom you're looking at is consumable.\n\nChoose mushrooms without white gills. Hunt for mushrooms with gills that are brown or tan. Whereas some mushrooms with white gills are eatable, the foremost dangerous and harmful mushroom family—Amanitas—nearly continuously have white gills.\n\nSelect mushrooms without ruddy on the cap or stem. Select mushrooms with white, tan or brown caps and stems. Numerous ruddy mushrooms are poisonous. A ruddy mushroom is utilizing its as it were normal caution framework, it’s color, to tell predators—including you—to control clear.\n\nLook for mushrooms without scales on the cap. Dodge mushrooms with patches or scaling of a lighter or darker shade on the cap, which may show up like spots. These flaky spots are common among noxious mushroom varieties. For illustration, white mushrooms may have tan or brown textured patches.\n\nSeek out mushrooms without a ring around the stem. Check underneath the cap of the mushroom for a moment veil-like ring of tissue that looks a bit like a mini-cap underneath the cap. In case the mushroom you’re watching has this ring of tissue, skip it. Numerous mushrooms with this highlight are poisonous.\n\nTake two wicker container after you scrounge. Put mushrooms you're sure are eatable in one bushel, and mushrooms you aren’t beyond any doubt approximately in another. You won’t get sick basically from taking care of a noxious mushroom. Counsel a learned master to recognize any mushrooms you aren’t beyond any doubt about. You can interface with a mushroom master through a local mycological bunch or at a nearby university. There isn't one specific area that eatable mushrooms develop. They can be found on trees, logs, the woodland floor, or on moss. There is no got to wear gloves when scrounging.\n\nDon’t ingest a mushroom unless you're 100% beyond any doubt of what it is. Utilize extraordinary caution when scrounging for mushrooms, as numerous noxious and nonpoisonous assortments see alike. A few assortments of mushrooms can alter their appearance depending upon developing conditions, making recognizable proof difficult. For case, mushrooms of the same assortment can create color in an unexpected way based on their presentation to sunlight. Experts recommend never eating any variety of mushroom that you simply haven’t been able to distinguish at least 3 times within the wild. A proficient ought to affirm merely have distinguished the mushroom legitimately each of those 3 times.\n""",
          'medicaltext':
              "\n\nLook for gastrointestinal disturbed inside 1-24 hours. Look for therapeutic treatment right absent in the event that you've got the runs, spewing, blood in your upchuck or stool, or intestinal cramping after ingesting unidentified mushrooms. Your neighborhood crisis room can supplant misplaced liquids and address any mushrooms harmfulness causing your symptoms. In a few cases, gastrointestinal indications can advance to disabled kidney work in case you don’t seek treatment right away. Even in the event that you are feeling humiliated at having eaten a possibly perilous mushroom, don't be bashful almost looking for treatment. Therapeutic professionals are as it were concerned approximately your wellbeing.\n\nPay consideration to intemperate salivation, tears, lactation, or sweating. Call crisis administrations right absent in case you take note an automatic anxious framework reaction, such as abundant and uncontrolled sweating or crying. These side effects can happen as rapidly as 15-30 minutes after ingesting a possibly hurtful mushroom. Act rapidly, as these indications can advance to visual unsettling influences, diminished blood weight, or trouble breathing. Due to the potential for a quick acceleration in involuntary-nervous-system indications, it’s best to call for offer assistance instead of endeavor to drive yourself to the crisis room. In crisis care, specialists can regulate Atropine, an cure that settle most of these indications. Most individuals make a full recuperation in 24 hours, but respiratory disappointment is conceivable without treatment.\n\nDon’t overlook any visual mutilations, fancies, or intemperate laziness. Look for crisis restorative administrations for any central nervous-system unsettling influences, such as languor or visualizations. Ingesting certain mushrooms can cause extreme central-nervous responses, such as writhings or indeed a coma. Medical groups can give steady care for any uneasiness and fluid-loss you experience. Typically these indications pass on their claim without causing long-term harm.\n\nStay careful for a reemergence of side effects after restorative treatment. Take note any inconvenience indications, either mental or physical, that repeat after you've got apparently “recovered” from your mushroom scene. Certain deadly mushrooms, such as those within the Amanita family, can cause a 24-hour period in which patients appear to progress some time recently backsliding and experiencing organ failure. If you've got any reason to accept you've got eaten an Amanita mushroom of any kind, don’t hold up for indications to seem. Seek crisis restorative care right absent. Let faculty know what kind of Amanita you have got ingested, how much you ate, and how recently. If you have got any pieces of the mushroom remaining, give them to the staff for examination.\n",
          'poisnoustext':
              "Are your mushrooms poisonous?\n\nIn the event that you come over a mushroom, some characterizing characteristics can assist you decide the plausibility of it being harmful. These aren't conclusive in that numerous consumable species moreover show these characteristics, but if you take note them, they are a great sign that you simply ought to take off the mushroom alone. You might miss out on a delightful treat, but more critical, you won't kick the bucket. And make no botch: Passing may be a genuine plausibility. A few 60 percent of cases including Amanita and other species result in passing. The tips are as takes after:\n\nMushrooms with white gills are frequently noxious. So are those with a ring around the stem and those with a volva. Since the volva is regularly underground, it's imperative to burrow around the base of a mushroom to seek for it.\n\nMushrooms with a ruddy color on the cap or stem are too either harmful or emphatically hallucinogenic. The foremost infamous red-colored mushroom is Amanita muscaria, which has been expended for thousands of a long time to deliver dreams. In expansive dosages, indeed this 'enchantment mushroom' can be deadly. Other Amanita species moreover have this coloration, and they are distant less kind.\n\nSAY NO TO DECAYED AND OLD MUSHROOMS: You would of course not pick decayed and old mushrooms but there is more to spotting the good ones from bad. While buying mushrooms make sure to check that they are fresh, firm and most importantly, whole. The mushroom should have no damage from any insects or animals. If you see that the mushroom is bitten, then do not buy it.\n\nDO NOT BUY PARASOL SHAPED (UMBRELLA-SHAPED) MUSROOMS: Avoid picking mushrooms that are in the shape of an umbrella and has white rings around the stem. These parasol-shaped mushrooms, which are also bright in colour, may be Amanitas mushrooms that are full of nature’s deadliest poison. These mushrooms get brown as they get older.\n\nAVOID FALSE MOREL MUSHROOMS: A mushroom with irregular and wrinkled cap that looks like a saddle should also not be consumed.\n\nOTHER WAYS: Sweet smelling mushrooms, Jack O’ Lantern and little brown mushrooms should also be avoided. Experienced people can easily distinguish between poisonous and non-poisonous mushrooms. If you do not have any experience at picking up mushrooms, avoid buying yourself as it may put you at risk.\n",
          'gallery': "Gallery",
          'camera': "Camera",
          'arama': "Mushroom Analysis",
          'poisonous': "Poisonous",
          'non-poisonous': "Non-Poisonous",
          'undefined': "Mushroom Unidentified",
          'pls': "Please wait..."
        },
        'tr_TR': {
          'mushrooms': "Mantarlar",
          'settings': "Ayarlar",
          'home': "Anasayfa",
          'language': "DİL AYARLARI",
          'social': "SOSYAL AĞLARIMIZ",
          'shareDeepMush': "DeepMush'ı PAYLAŞ",
          'share_rate': "DeepMush'ı Paylaş ve Puanla",
          'feedback': "GERİ BİLDİRİM BIRAK",
          'rate_mail': "DeepMush'ı Oyla veya Bizimle İletişime Geç",
          'toastgoogleplay': "Google Play'e Yönlendiriliyorsunuz",
          'toastmail': "Mail'e Yönlendiriliyorsunuz",
          'toastgallery': "Lütfen bir fotoğraf seçin",
          'toastcamera': "Lütfen bir fotoğraf çekin",
          'moreinfo': "Daha fazlası için tıkla",
          'medicalassitance': "Tıbbi Yardım",
          'ediblemushrooms': "Yenilebilir Mantarlar",
          'poisonousmushrooms': "Zehirli Mantarlar",
          'whatdeepmush': "DeepMush NEDİR?",
          'whatdeepmushtext':
              "DeepMush, yapay zeka kullanılarak geliştirilmiş bir uygulamadır. DeepMush, dünyadaki en yaygın zehirli ve zehirsiz mantarların yaklaşık yirmi bin görüntüsü toplanarak yapay zeka kullanılarak geliştirildi. DeepMush'ın amacı yalnızca BİLGİ amaçlıdır. Mantar toplamak ve tanımlamak kesinlikle bir uzmanlık meselesidir. DeepMush'taki bilgilere göre mantar toplamanızı veya tüketmenizi önermiyoruz!\n",
          'howisworking': "NASIL ÇALIŞIYOR",
          'howisworkingtext':
              "Uygulama Yapay Zeka ile çalışmaktadır. Uygulama için yaklaşık yirmi bin mantar görüntüsü toplanmış ve bu görüntüler kullanılarak Derin Öğrenme ağı eğitilmiştir. Ağ yapısı olarak CNN (Convolutional Neural Network) kullanılmış ve Keras kütüphanesi kullanılmıştır.\n",
          'attention': "DİKKAT\n",
          'attentiontext':
              "Bu uygulama yalnızca BİLGİLENDİRME amacıyla oluşturulmuştur ve ürünlerin yenilebilirliğini kontrol etmek için kullanılmasını önermiyoruz. Olası tehlikeler ve hatalardan sorumlu değiliz.\n\n DeepMush'ın amacı yalnızca BİLGİ amaçlıdır. Mantar toplamak ve tanımlamak kesinlikle bir uzmanlık meselesidir. DeepMush'taki bilgilere göre mantar toplamanızı veya tüketmenizi önermiyoruz!\n",
          'mushroomstext':
              """Her şeyden önce, bir mantarın yenilebilirliği kesinleşmişse o mantarı yiyebilirsiniz ama mantarlar hakkında bilginiz yok ise mantarlardan uzak durmanızda fayda var. Eğer bilmediğiniz bir mantarı yerseniz, bu mantar sizi hasta edebilir daha kötüsü sizi öldürebilir. Bir mantarın makul derecede güvenli olduğunu düşünüyorsanız veya tamamen şüphe duymuyorsanız, bu sağlığınızı tehlikeye atmanız demektir. Lütfen uygulamadaki bilgilere dayanarak tehlikeli bir şey yapmayız.\n\nMantarların yapısı aşağıdaki gibidir. Mantarın bu bölgelerine bakarak bir mantarın zehirli olup olmadığını anlayabilirsiniz.\n\n""",
          'attentiongiris':
              "Bu uygulama yalnızca BİLGİLENDİRME amacıyla oluşturulmuştur ve ürünlerin yenilebilirliğini kontrol etmek için kullanılmasını önermiyoruz. Mantar toplamak ve tanımlamak kesinlikle bir uzmanlık meselesidir. DeepMush'ta yer alan bilgilere göre mantar toplamanızı veya tüketmenizi önermiyoruz. Olası tehlikeler ve hatalardan sorumlu değiliz.",
          'agree': "Kabul Ediyorum",
          'takephptporgalery': "Fotoğraf Çek veya Galeriden Seç",
          'dg': "Doğruluk Yüzdesi",
          '0 Poisonous': "0 Zehirli",
          '1 Edible': "1 Yenilir",
          '2 Undefined': "2 Tanımsız",
          'share': "Paylaş",
          'rate': "Oyla",
          'contact': "Bize Ulaş",
          'mushroomstext2':
              """Şapka: Şapka, mantarın en iyisidir (ve genellikle küçük bir şemsiye gibi görünür). Mantar Şapkaları çeşitli renklerde olabilir, ancak çoğu zaman kahverengi, beyaz veya sarıdır.\n\nSolungaçlar, Gözenekler veya Dişler: Bu yapılar mantarın başlığının altında görünür.\n\nYüzük: Halka (zamanın bir kısmı halka olarak adlandırılır), solungaçlar geçtikten sonra fraksiyonel pelerin yapısıdır.\n\nKök veya Stipe: Başlığı yerden yüksekte tutan yüksek yapı.\n\nVolva: Volva, mantar yerden büyüdükten sonra kalan savunma pelerini. Organizma geliştikçe volvayı yarıp geçer.\n\nSporlar: Yenileyici operatörler olarak hareket eden küçük tohumlar; normalde tartışmaya boşaltılırlar ve kullanılmayan bir mantar oluşturmak için bir alt tabakaya bırakılırlar.\n""",
          'edibletext':
              """Dışarıda zaman geçirmeniz durumunda, ağaçların altında veya bahçenizde mantarların geliştiğini görmüşsünüzdür, baktığınız mantarın tüketilebilir olduğunu anlamanın birkaç yolu var. Bu bilgilere dışarıda kamp yapıyorsanız ihtiyacınız olabilir.\n\nBeyaz solungaçları olmayan mantarları seçin. Kahverengi veya ten rengi solungaçlı mantarları avlayın. Beyaz solungaçlı mantarlar yenilebilirken, en önemli tehlikeli ve zararlı mantar ailesi — Amanitas — neredeyse sürekli olarak beyaz solungaçlara sahiptir.\n\nKapağında veya gövdesinde kırmızı olmayan mantarları seçin. Beyaz, ten rengi veya kahverengi başlıklı ve saplı mantarları seçin. Kırmızı mantarların çoğu zehirlidir. Kırmızı bir mantar gördüyseniz kesinlikle uzak durmalısınız. \n\nKapağında pul bulunmayan mantarları arayın. Kapağında lekeler gibi görünebilen yamalar veya daha açık mantarlardan kaçının. Bu beyaz lekeler, zararlı mantar çeşitleri arasında yaygındır.\n\nSap çevresinde halka olmadan mantarları ayıklayın. Mantarın kapağının altında, kapağın altında mini bir kapağa benzeyen bir peçe benzeri doku halkası olup olmadığına bakın. İzlediğiniz mantar bu doku yüzüğüne sahipse, kesinlikle uzak durun. Bu özelliğe sahip çok sayıda mantar zehirlidir.\n\nİki kap alın. Yenilebilir olduğundan emin olduğunuz mantarları ve şüphe duyduğunuz mantarlarıda diğer kaba koyun. Bu konu hakkında bilgili bir kişiye danışarak edindiğiniz bilgiler çerçevesinden mantarları tüketin. Yenilebilir mantarların geliştiği belirli bir alan yoktur. Ancak genelde ağaçlarda, kütüklerde, ormanlık zeminde veya yosunlarda bulunabilirler. Bu mantarları toplarken eldiven takmanıza gerek yok.\n\nNe olduğundan% 100 emin olmadığınız sürece mantar yemeyin. Çok sayıda zehirli ve zehirsiz ürün çeşidinin benzer göründüğü gibi mantarları tararken çok fazla dikkatli olun. Birkaç mantar çeşidi, gelişen koşullara bağlı olarak görünüşlerini değiştirebilir ve bu da tanınabilirliğini zorlaştırabilir. Durum için, aynı çeşitteki mantarlar, güneş ışığına sunumlarına bağlı olarak beklenmedik bir şekilde renk oluşturabilir. Uzmanlar, vahşi doğada ayırt edemediğiniz mantar çeşitlerini asla yememenizi tavsiye ediyor. Bu uygulamdaki yazılar yanlızca BİLGİLENDİRME amaçlıdır. Buradaki bilgilere göre mantar toplanmasını önermiyoruz. Mantar toplamak uzmanlık isteyen bir konudur.\n""",
          'medicaltext':
              "\n\n1-24 saat içinde gastrointestinal rahatsızlık olup olmadığına bakın. Tanımlanamayan mantarları yedikten sonra akıntılarınız, kusmanız, sarkıklığınızda veya dışkınızda kanınız olması veya bağırsakta kramp olmanız durumunda, hemen sağlık ekiblerini arayın. Eğer mantardan zehirlendiyseniz ve hemen tedaviye başlamazsanız, gastrointestinal endikasyonlar böbreklere ilerleyebilir. Muhtemelen tehlikeli bir mantarı yemekten dolayı kendinize kızıyor olsanız bile, hiç öekinmedn sağlık ekibini arayın.n\n\nAğırlıklı tükürük, gözyaşı veya terlemeyi göz önünde bulundurun. Bol ve kontrolsüz terleme veya ağlama gibi kendinizi kontrol edemiyorsanız  kriz yönetimlerini hemen arayın. Bu yan etkiler, muhtemelen zehirli bir mantarı yedikten 15-30 dakika sonra ortaya çıkabilir. Bu belirtiler görsel rahatsız edici etkilere, azalan kan dolaşımı veya solunum güçlüğüne ilerleyebileceğinden hızlı hareket edin. İstemsiz sinir sistemi belirtilerindeki hızlı hızlanma potansiyeli nedeniyle, kendinizi kriz odasına götürmeye çalışmak yerine teklif yardımını aramak en iyisidir. Kriz tedavisinde uzmanlar, bu endikasyonların çoğunu ortadan kaldıran bir tedavi olan Atropin'i düzenleyebilir. Çoğu kişi 24 saat içinde tamamen iyileşir, ancak solunum yetmezliği tedavi olmaksızın düşünülebilir.\n\nHerhangi bir görsel sakatlığı, hayalleri veya aşırı tembelliği görmezden gelmeyin. Halsizlik veya görselleştirme gibi merkezi sinir sistemini rahatsız eden herhangi bir etki için krizi iyileştirici yönetimleri arayın. Bazı mantarların yutulması, kıvranmalar veya aslında koma gibi aşırı merkezi sinir tepkilerine neden olabilir. Tıbbi gruplar, yaşadığınız herhangi bir rahatsızlık ve sıvı kaybı için sürekli bakım sağlayabilir. Tipik olarak bu endikasyonlar, uzun vadeli bir zarara yol açmadan iddialarını iletir.\n\nResaratif tedaviden sonra yan etkilerin yeniden ortaya çıkması için dikkatli olun. Mantar sahnenizden görünüşte 'iyileştikten' sonra tekrarlayan zihinsel veya fiziksel herhangi bir rahatsızlık belirtisini not edin. Amanita ailesindekiler gibi bazı ölümcül mantarlar, hastaların son zamanlarda bir süre geriye kayarak ve organ yetmezliği yaşadıkları görüldüğü 24 saatlik bir süreye neden olabilir. Herhangi bir tür Amanita mantarı yediğinizi kabul etmek için herhangi bir sebebiniz varsa, belirtilerin görünmesi için beklemeyin. Yoksun krizi onarıcı bakım isteyin. Fakülte ne tür Amanita yediğinizi, ne kadar yediğinizi ve ne kadar yakın zamanda yediğinizi bilmesini sağlayın. Kalan mantar parçanız varsa, bunları incelenmek üzere personele verin.\n",
          'poisnoustext':
              "Mantarlarınız zehirli mi? \n\nBir mantarın üzerine geldiğinizde, bazı karakterize edici özellikler onun zararlı olup olmadığına karar vermenize yardımcı olabilir. Bunlar, çok sayıda tüketilebilir türün bu özellikleri gösterdiği için kesin değildir, ancak bunları not alırsanız, mantarı tek başına çıkarmanız gerektiğine dair harika bir işarettir. Keyifli bir ziyafeti kaçırabilirsiniz, ancak daha da önemlisi, kovayı tekmelemeyeceksiniz. Ve hiçbir şey yapmayın: Pas vermek gerçek bir akla yatkınlık olabilir. Amanita ve diğer türler de dahil olmak üzere vakaların birkaç yüzde 60'ı ölümle sonuçlanıyor. İpuçları aşağıdaki gibidir: \n\nBeyaz solungaçlı mantarlar genellikle zararlıdır. Gövde çevresinde halka olanlar ve volvası olanlar da öyle. Volva düzenli olarak yeraltında olduğundan, onu aramak için bir mantarın tabanının etrafına oymak zorunludur. \n\nKapağında veya gövdesinde kırmızı bir renk olan mantarlar çok zararlıdır veya kesinlikle halüsinojendir. En önde gelen kötü şöhretli kırmızı renkli mantar, hayalleri gerçekleştirmek için binlerce uzun süredir harcanan Amanita muscaria'dır. Geniş dozajlarda, gerçekten de bu 'büyü mantarı' ölümcül olabilir. Üstelik diğer Amanita türleri bu renklenmeye sahiptir ve uzaktaki daha az naziktirler. \n\nÇürümüş ve yaşlı mantarları seçmeyin: Elbette çürümüş ve eski mantarları seçmezsiniz, ancak iyi olanları kötüden ayırt etmek için daha fazlası vardır. Mantar satın alırken taze, sağlam ve en önemlisi bütün olup olmadıklarını mutlaka kontrol edin. Mantar, böcek veya hayvanlardan zarar görmemelidir. Mantarın ısırıldığını görürseniz satın almayın. \n\nPARASOL ŞEKİLLİ (ŞEMSİYE ŞEKLİNDE) MÜZROOMLAR: Şemsiye şeklinde ve gövdesi etrafında beyaz halkalar olan mantarları toplamaktan kaçının. Rengi de parlak olan bu şemsiye şeklindeki mantarlar, doğanın en ölümcül zehiriyle dolu Amanitas mantarları olabilir. Bu mantarlar yaşlandıkça kahverengileşir. \ N \ nAVOID YANLIŞ MOREL MANTARLAR: Eyer gibi görünen düzensiz ve buruşuk başlıklı mantar da tüketilmemelidir. \n\nDİĞER YOLLAR: Tatlı kokulu mantarlar, Jack O 'Lantern ve küçük kahverengi mantarlardan da kaçınılmalıdır. Deneyimli insanlar zehirli ve zehirsiz mantarları kolaylıkla ayırt edebilir. Mantar toplama konusunda herhangi bir deneyiminiz yoksa, kendinizi riske atabileceğinden kendinizi satın almaktan kaçının.\n",
          'gallery': "Galeri",
          'camera': "Kamera",
          'arama': "Mantar Analizi",
          'poisonous': "Zehirli",
          'non-poisonous': "Zehirsiz",
          'undefined': "Mantar Tanımlanamadı",
          'pls': "Lütfen Bekleyin...",
        }
      };
}
